### ISSUE TITLE
FreeBSD build error

### ISSUE THREAD

**Issue by biancalana** [mark-5/p5-zookeeper#1]
I've installed zookeeper and libzookeeper but I'm getting the following error when trying to compile this module https://gist.github.com/biancalana/b7561d0c564c6066afef

**Comment by mark-5** [comment]
This appears to be an issue with threaded perls. I just pushed the fix for this to master, and I can have this released to CPAN later tonight.

**Comment by mark-5** [comment]
ZooKeeper-0.0.10 has been uploaded, and should have propagated to most CPAN mirrors by now. Could you try building the new release, whenever you get a chance?

**Comment by biancalana** [comment]
:+1: fixed !
