### ISSUE TITLE
Blobs containing NUL bytes are truncated when written to ZooKeeper nodes

### ISSUE THREAD

**Issue by fgabolde** [mark-5/p5-zookeeper#2]
See the gist here: https://gist.github.com/fgabolde/f223f51fa260e74c7cac

When writing a binary blob that contains the null character, only the bytes up to the null character are written to the ZK node. You can check using zkCli that the node written to `/zksereal/sereal` is indeed only 5 bytes long even though it should be 37 bytes long.

This is not limited to Sereal either, I originally found the issue when trying to fetch HBase-owned nodes which contain protobuf blobs. Sereal is just what I had on hand when trying to replicate the issue.

Net::ZooKeeper does not seem to be affected.

**Comment by mark-5** [comment]
Whoops, looks like create and set were expecting standard C strings, and using functions like strlen to calculate string length. create, get, and set should all be fixed now.

**Comment by mark-5** [comment]
FYI I'm reopening this because I just realized this hasn't been properly fixed for transactions.

**Comment by fgabolde** [comment]
Neat, thanks for the quick response.

I'll try this at work on Monday.

**Comment by fgabolde** [comment]
@mark-5 Yup, it roundtrips nicely now. Thanks again!
